import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Clock, ShieldCheck, ArrowLeft, Download } from 'lucide-react';
import { SalaryBreakdownCard } from '../components/PayrollCards';
import { PayrollStatusBadge, TaxComponentBadge } from '../components/PayrollBadges';
import { AuditTimeline } from '../components/PayrollTimelines';
import api from '../../../lib/axios';

/**
 * PayrollDetailsPage.jsx
 * Comprehensive audit & financial breakdown of an individual payroll run or employee record.
 * Displays Payroll Summary, Salary Breakdown, Attendance Summary, Leave Impact, Tax Summary, and Audit Timeline.
 */

export const PayrollDetailsPage = ({ onBack, onNavigate, record }) => {
  const [activeTab, setActiveTab] = useState('breakdown');

  const payrollId = record?.id || record?._id;

  const { data: detailData, isLoading } = useQuery({
    queryKey: ['payroll-detail', payrollId],
    queryFn: () => api.get(`/payroll/${payrollId}`).then(r => r.data),
    enabled: !!payrollId
  });

  const raw = detailData?.data || detailData;

  const runInfo = raw ? {
    id: raw._id || raw.id,
    month: new Date(raw.payPeriodYear, raw.payPeriodMonth - 1).toLocaleString('default', { month: 'long' }),
    year: String(raw.payPeriodYear),
    status: raw.status || 'PENDING_APPROVAL',
    totalGross: raw.totalGrossPay || raw.grossPay || 0,
    totalDeductions: raw.totalDeductions || raw.deductionTotal || 0,
    totalNet: raw.totalNetPay || raw.netPay || 0,
    empCount: raw.employeeCount || 0,
    lopDays: raw.lopDays || 0,
    lopAmount: raw.lopAmount || 0,
    tds: raw.totalTax || raw.tds || 0,
    pf: raw.totalPf || raw.pf || 0,
    esi: raw.totalEsi || raw.esi || 0,
    pt: raw.totalPt || raw.pt || 0
  } : {
    id: 'PR-—',
    month: '—',
    year: '—',
    status: 'PENDING_APPROVAL',
    totalGross: 0,
    totalDeductions: 0,
    totalNet: 0,
    empCount: 0,
    lopDays: 0,
    lopAmount: 0,
    tds: 0,
    pf: 0,
    esi: 0,
    pt: 0
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header Bar */}
      <div className="bg-[#ffffff] dark:bg-[#111111] border border-[#e1e2ed] dark:border-gray-800 rounded-lg p-5 shadow-xs flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          {onBack && (
            <button
              onClick={onBack}
              className="p-2 bg-[#ededf9] hover:bg-[#e1e2ed] dark:bg-gray-800 dark:hover:bg-gray-700 rounded text-[#191b23] dark:text-white transition-colors"
              title="Back"
            >
              <ArrowLeft size={16} />
            </button>
          )}
          <div>
            <div className="flex items-center gap-2 mb-1">
              <h1 className="text-lg sm:text-xl font-bold text-[#191b23] dark:text-white">
                {runInfo.month} {runInfo.year} Payroll Run Details
              </h1>
              <PayrollStatusBadge status={runInfo.status} />
            </div>
            <p className="text-xs text-[#737686] dark:text-gray-400 font-mono">
              Run ID: {runInfo.id} • Generated by System Auto • 342 Active Staff Processed
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => alert('Exporting complete detailed calculation sheet to Excel...')}
            className="px-3.5 py-2.5 bg-[#ededf9] hover:bg-[#e1e2ed] dark:bg-gray-800 dark:hover:bg-gray-700 text-[#191b23] dark:text-white text-xs font-semibold rounded inline-flex items-center gap-1.5 transition-colors"
          >
            <Download size={14} /> Export Calculation Sheet
          </button>
          {onNavigate && (
            <button
              onClick={() => onNavigate('approval')}
              className="px-4 py-2.5 bg-[#2563eb] hover:bg-[#004ac6] text-white text-xs font-semibold rounded inline-flex items-center gap-1.5 transition-colors shadow-xs"
            >
              <ShieldCheck size={14} /> Proceed to Approval
            </button>
          )}
        </div>
      </div>

      {/* Hero Financial Summary Banner */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-[#faf8ff] dark:bg-gray-900/40 border border-[#e1e2ed] dark:border-gray-800 rounded-lg p-4">
          <span className="text-xs font-semibold text-[#737686] block">Gross Disbursal Commitment</span>
          <span className="text-xl sm:text-2xl font-extrabold font-mono text-[#191b23] dark:text-white mt-1 block">
            ₹{runInfo.totalGross.toLocaleString('en-IN')}
          </span>
          <span className="text-[11px] text-[#737686] mt-0.5 block">CTC before taxes & LOP</span>
        </div>
        <div className="bg-rose-50/40 dark:bg-rose-950/20 border border-rose-200 dark:border-rose-900/40 rounded-lg p-4">
          <span className="text-xs font-semibold text-rose-800 dark:text-rose-300 block">Total Deductions & Taxes</span>
          <span className="text-xl sm:text-2xl font-extrabold font-mono text-rose-600 mt-1 block">
            -₹{runInfo.totalDeductions.toLocaleString('en-IN')}
          </span>
          <span className="text-[11px] text-rose-700 dark:text-rose-400 mt-0.5 block">PF, ESI, TDS, PT & LOP</span>
        </div>
        <div className="bg-emerald-50/50 dark:bg-emerald-950/20 border border-emerald-200 dark:border-emerald-900/40 rounded-lg p-4">
          <span className="text-xs font-semibold text-emerald-800 dark:text-emerald-300 block">Net Payable Disbursal</span>
          <span className="text-xl sm:text-2xl font-extrabold font-mono text-emerald-600 mt-1 block">
            ₹{runInfo.totalNet.toLocaleString('en-IN')}
          </span>
          <span className="text-[11px] text-emerald-700 dark:text-emerald-400 mt-0.5 block">Direct Bank Transfer</span>
        </div>
        <div className="bg-[#ffffff] dark:bg-[#111111] border border-[#e1e2ed] dark:border-gray-800 rounded-lg p-4 flex flex-col justify-between">
          <span className="text-xs font-semibold text-[#737686] block">Headcount & LOP Impact</span>
          <div className="flex items-baseline justify-between mt-1">
            <span className="text-lg font-extrabold font-mono text-[#2563eb]">{runInfo.empCount} Staff</span>
            <span className="text-xs font-mono font-bold text-amber-600">{runInfo.lopDays} LOP Days</span>
          </div>
          <span className="text-[11px] text-[#737686] mt-0.5 block">Unpaid absence savings: ₹42,000</span>
        </div>
      </div>

      {/* Tabs Toolbar */}
      <div className="flex border-b border-[#e1e2ed] dark:border-gray-800 gap-6 text-xs font-bold font-mono">
        {[
          { id: 'breakdown', label: 'Salary Structure Breakdown' },
          { id: 'attendance', label: 'Attendance & Leave Impact (LOP)' },
          { id: 'tax', label: 'Statutory Tax Summary' },
          { id: 'audit', label: 'Audit Timeline' },
        ].map((t) => (
          <button
            key={t.id}
            onClick={() => setActiveTab(t.id)}
            className={`pb-3 border-b-2 transition-all ${
              activeTab === t.id
                ? 'border-[#2563eb] text-[#2563eb]'
                : 'border-transparent text-[#737686] hover:text-[#191b23] dark:hover:text-white'
            }`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* Tab Content 1: Salary Breakdown */}
      {activeTab === 'breakdown' && (
        <div className="space-y-6">
          <SalaryBreakdownCard
            employeeName="Organization Consolidated Average (342 Employees)"
            basic={3050000}
            allowances={3050000}
            deductions={830000}
            tax={420000}
            net={4850000}
          />

          {/* Sample Employee List Breakdown */}
          <div className="bg-[#ffffff] dark:bg-[#111111] border border-[#e1e2ed] dark:border-gray-800 rounded-lg overflow-hidden shadow-xs">
            <div className="p-4 bg-[#ededf9] dark:bg-gray-900 border-b border-[#e1e2ed] dark:border-gray-800 font-bold text-xs">
              Employee Salary Breakdown Ledger (Top Records)
            </div>
            <div className="overflow-x-auto">
              <table>
                <thead>
                  <tr>
                    <th>Employee / ID</th>
                    <th>Department</th>
                    <th className="text-right">Basic Salary</th>
                    <th className="text-right">Allowances</th>
                    <th className="text-right">Statutory Deductions</th>
                    <th className="text-right">TDS Tax</th>
                    <th className="text-right">Net Payable</th>
                  </tr>
                </thead>
                <tbody>
                  {[
                    { name: 'Sarah SDE-II', id: 'EMP-0142', dept: 'Engineering', basic: 85000, all: 45000, ded: 12500, tds: 8500, net: 109000 },
                    { name: 'John DevOps', id: 'EMP-0089', dept: 'Engineering', basic: 75000, all: 40000, ded: 11000, tds: 5500, net: 98500 },
                    { name: 'Emily HR Specialist', id: 'EMP-0034', dept: 'HR', basic: 65000, all: 32000, ded: 9500, tds: 3500, net: 84000 },
                    { name: 'David Finance Mgr', id: 'EMP-0012', dept: 'Finance', basic: 110000, all: 60000, ded: 14500, tds: 10500, net: 145000 },
                  ].map((row, idx) => (
                    <tr key={idx}>
                      <td className="font-bold text-xs">{row.name} <span className="font-mono text-[#737686] block text-[11px]">{row.id}</span></td>
                      <td className="text-xs text-[#737686]">{row.dept}</td>
                      <td className="text-right font-mono">₹{row.basic.toLocaleString('en-IN')}</td>
                      <td className="text-right font-mono">₹{row.all.toLocaleString('en-IN')}</td>
                      <td className="text-right font-mono text-rose-600">-₹{row.ded.toLocaleString('en-IN')}</td>
                      <td className="text-right font-mono text-rose-600">-₹{row.tds.toLocaleString('en-IN')}</td>
                      <td className="text-right font-mono font-bold text-emerald-600">₹{row.net.toLocaleString('en-IN')}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* Tab Content 2: Attendance & Leave Impact */}
      {activeTab === 'attendance' && (
        <div className="bg-[#ffffff] dark:bg-[#111111] border border-[#e1e2ed] dark:border-gray-800 rounded-lg p-6 shadow-xs space-y-6">
          <div className="flex items-center justify-between pb-4 border-b border-[#e1e2ed] dark:border-gray-800">
            <div>
              <h3 className="text-sm font-bold text-[#191b23] dark:text-white flex items-center gap-2">
                <Clock size={16} className="text-[#2563eb]" />
                ATTENDANCE SUMMARY & LOSS OF PAY (LOP) IMPACT
              </h3>
              <p className="text-xs text-[#737686] mt-0.5">Automated synchronization with Attendance and Leave Management modules.</p>
            </div>
            <span className="text-xs font-mono font-bold px-3 py-1 bg-amber-50 text-amber-800 dark:bg-amber-950/40 dark:text-amber-300 rounded border border-amber-200">
              Total LOP Deductions: -₹42,000 (14 Days)
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
            <div className="p-4 bg-[#faf8ff] dark:bg-gray-900/40 rounded border border-[#e1e2ed]/60">
              <span className="text-[#737686] block font-semibold">Total Working Days (July 2026)</span>
              <span className="text-xl font-mono font-extrabold text-[#191b23] dark:text-white mt-1 block">22 Days</span>
              <span className="text-[11px] text-[#737686] mt-0.5 block">Excluding 8 weekends + 1 holiday</span>
            </div>
            <div className="p-4 bg-[#faf8ff] dark:bg-gray-900/40 rounded border border-[#e1e2ed]/60">
              <span className="text-[#737686] block font-semibold">Staff Paid Leave Utilized</span>
              <span className="text-xl font-mono font-extrabold text-[#2563eb] mt-1 block">184 Days</span>
              <span className="text-[11px] text-emerald-600 font-bold mt-0.5 block">100% covered by available quota</span>
            </div>
            <div className="p-4 bg-rose-50/40 dark:bg-rose-950/20 rounded border border-rose-200">
              <span className="text-rose-800 dark:text-rose-300 block font-semibold">Unauthorized Absence / LOP</span>
              <span className="text-xl font-mono font-extrabold text-rose-600 mt-1 block">14 Days</span>
              <span className="text-[11px] text-rose-700 dark:text-rose-400 mt-0.5 block">Deducted from basic CTC salary</span>
            </div>
          </div>
        </div>
      )}

      {/* Tab Content 3: Statutory Tax Summary */}
      {activeTab === 'tax' && (
        <div className="bg-[#ffffff] dark:bg-[#111111] border border-[#e1e2ed] dark:border-gray-800 rounded-lg p-6 shadow-xs space-y-6">
          <div className="flex items-center justify-between pb-4 border-b border-[#e1e2ed] dark:border-gray-800">
            <div>
              <h3 className="text-sm font-bold text-[#191b23] dark:text-white flex items-center gap-2">
                <ShieldCheck size={16} className="text-emerald-600" />
                STATUTORY TAX & RETIREMENT WITHHOLDINGS SUMMARY
              </h3>
              <p className="text-xs text-[#737686] mt-0.5">Compliance verification for Indian Labour Law & Income Tax requirements.</p>
            </div>
            <span className="text-xs font-mono font-bold text-emerald-600">100% Compliant</span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 text-xs">
            <div className="p-4 bg-blue-50/50 dark:bg-blue-950/20 rounded border border-blue-200">
              <TaxComponentBadge type="PF" />
              <span className="text-lg font-mono font-extrabold text-[#191b23] dark:text-white mt-2 block">₹5,80,000</span>
              <span className="text-[11px] text-[#737686] block mt-0.5">12% Employee + 12% Employer</span>
            </div>
            <div className="p-4 bg-purple-50/50 dark:bg-purple-950/20 rounded border border-purple-200">
              <TaxComponentBadge type="ESI" />
              <span className="text-lg font-mono font-extrabold text-[#191b23] dark:text-white mt-2 block">₹1,10,000</span>
              <span className="text-[11px] text-[#737686] block mt-0.5">0.75% + 3.25% contribution</span>
            </div>
            <div className="p-4 bg-amber-50/50 dark:bg-amber-950/20 rounded border border-amber-200">
              <TaxComponentBadge type="PT" />
              <span className="text-lg font-mono font-extrabold text-[#191b23] dark:text-white mt-2 block">₹68,400</span>
              <span className="text-[11px] text-[#737686] block mt-0.5">Fixed state professional tax</span>
            </div>
            <div className="p-4 bg-rose-50/50 dark:bg-rose-950/20 rounded border border-rose-200">
              <TaxComponentBadge type="TDS" />
              <span className="text-lg font-mono font-extrabold text-rose-600 mt-2 block">₹4,20,000</span>
              <span className="text-[11px] text-[#737686] block mt-0.5">Income tax withholding</span>
            </div>
          </div>
        </div>
      )}

      {/* Tab Content 4: Audit Timeline */}
      {activeTab === 'audit' && (
        <AuditTimeline />
      )}
    </div>
  );
};
