/**
 * Payslip.js
 * Mongoose Schema for Payslips Collection
 * Generated payslip documents. Stores payslip PDF URL and structured display data.
 *
 * Authority: DATABASE_DESIGN.md Section 7.13
 */

const mongoose = require('mongoose');

const payslipSchema = new mongoose.Schema(
  {
    payrollId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Payroll',
      required: [true, 'Payroll ID is required'],
      unique: true,
    },
    employeeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Employee',
      required: [true, 'Employee ID is required'],
    },
    organizationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Organization',
      required: [true, 'Organization ID is required'],
    },
    payPeriodMonth: {
      type: Number,
      required: [true, 'Pay period month is required'],
      min: [1, 'Month must be between 1 and 12'],
      max: [12, 'Month must be between 1 and 12'],
    },
    payPeriodYear: {
      type: Number,
      required: [true, 'Pay period year is required'],
      min: [2000, 'Invalid year'],
      max: [2100, 'Invalid year'],
    },
    payslipUrl: {
      type: String,
      default: null,
    },
    payslipPublicId: {
      type: String,
      default: null,
    },
    generatedAt: {
      type: Date,
      required: [true, 'Generated timestamp is required'],
    },
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Generated by User ID is required'],
    },
    isEmailSent: {
      type: Boolean,
      required: true,
      default: false,
    },
    emailSentAt: {
      type: Date,
      default: null,
    },
    status: {
      type: String,
      required: true,
      enum: ['active', 'archived'],
      default: 'active',
    },
  },
  {
    timestamps: { createdAt: true, updatedAt: false }, // Immutable generated document
  }
);

// Indexes
payslipSchema.index({ employeeId: 1, payPeriodYear: 1, payPeriodMonth: 1 });
payslipSchema.index({ employeeId: 1 });

module.exports = mongoose.model('Payslip', payslipSchema);
